/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LogInUsers;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import patientmanagementsystem.ReadJSONFile;
import patientmanagementsystem.WriteJSONFile;
import patientmanagementsystem.login_CreateAcc;

/**
 *
 * @author jbridgman2
 */
public class LogInScreen extends javax.swing.JFrame {

    //private boolean isUser;
    private ReadJSONFile read = new ReadJSONFile();
    /**
     * Creates new form LogInScreen
     */
    public LogInScreen() {
        initComponents();
        ClearText();
        //read.ReadInUsers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login_btn = new javax.swing.JButton();
        Logon_lbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        User_lbl = new javax.swing.JLabel();
        Password_lbl = new javax.swing.JLabel();
        User_txt = new javax.swing.JTextField();
        Password_pfield = new javax.swing.JPasswordField();
        Exit_btn = new javax.swing.JButton();
        CreateAcc_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Login_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Login_btn.setText("Login");
        Login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_btnActionPerformed(evt);
            }
        });

        Logon_lbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Logon_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logon_lbl.setText("Log On");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        User_lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        User_lbl.setText("USER ID:");

        Password_lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Password_lbl.setText("PASSWORD:");
        Password_lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Password_lbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Password_lbl.setName(""); // NOI18N

        User_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        User_txt.setText("jTextField1");
        User_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_txtActionPerformed(evt);
            }
        });

        Password_pfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Password_pfield.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(User_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Password_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(User_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(Password_pfield, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(User_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(User_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Password_pfield, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        Exit_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Exit_btn.setText("Exit");
        Exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_btnActionPerformed(evt);
            }
        });

        CreateAcc_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CreateAcc_btn.setText("Create Account");
        CreateAcc_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAcc_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Logon_lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CreateAcc_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Login_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Exit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logon_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Login_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CreateAcc_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void User_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_User_txtActionPerformed

    private void Login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_btnActionPerformed
        //CheckDetails();
        //LoggingIn();
        CheckLoginUser();
    }//GEN-LAST:event_Login_btnActionPerformed

    private void Exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_btnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Exit_btnActionPerformed

    private void CreateAcc_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAcc_btnActionPerformed
        login_CreateAcc createAcc = new login_CreateAcc();
        createAcc.setVisible(true);
        
        CloseLogin();
    }//GEN-LAST:event_CreateAcc_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
        
        new LogInScreen().setVisible(true);
    }

    private void CheckLoginUser(){
        
        //read.ReadInPatientsDetails();
        //read.ReadInDoctorsDetails();
        
        String inputID = User_txt.getText().toLowerCase();
        String inputPW = Password_pfield.getText();
        
        if(read.ReadInUsers(inputID, inputPW)){
            System.out.println("login");
            
            char firstLetter = inputID.charAt(0);
            
            // STRAT PATTERN
            switch(firstLetter){
                case 'a':
                    User_Administrator Admin = new User_Administrator(inputID);
                    Admin.setVisible(true);
                    CloseLogin();
                    break;
                case 's':
                    User_Secretary Secretary = new User_Secretary(inputID);
                    Secretary.setVisible(true);
                    CloseLogin();
                    break;
                case 'd':
                    User_Doctor Doctor = new User_Doctor(inputID);
                    Doctor.setVisible(true);
                    CloseLogin();
                    break;
                case 'p':
                    User_Patient Patient = new User_Patient(inputID);
                    Patient.setVisible(true);
                    CloseLogin();
                    break;
            }
        }
        else 
        {
            System.out.println("Invalid username or password");
              JOptionPane.showMessageDialog(null, "Invalid Login Details", 
                "Login Error", JOptionPane.ERROR_MESSAGE);
            ClearText();
            
            System.out.println("enter correct detials");
        } 
    }
    
    private void LoggingIn(){
        String userId;
        String password;
        
        User loggedInUser = null;
        
        List<User> listOfUsers = new ArrayList<>();
        
        listOfUsers.add(new User("a", "1", "Admin"));
        listOfUsers.add(new User("s", "2", "Secretary"));
        listOfUsers.add(new User("d1", "31", "DR. Park"));
        listOfUsers.add(new User("d2", "32", "DR. Bench"));
        listOfUsers.add(new User("d3", "33", "DR. Water"));
        listOfUsers.add(new User("p1", "41", "Patrick"));
        listOfUsers.add(new User("p2", "42", "Penny"));
        listOfUsers.add(new User("p3", "43", "Peter"));
        
        //WriteJSONFile file = new WriteJSONFile(listOfUsers);
        
        userId = User_txt.getText().toLowerCase();
        password = Password_pfield.getText();
        
        for(User user : listOfUsers){
            if(user.getUserID().equals(userId)) {
                if(user.getPassword().equals(password)){
                    loggedInUser = user;
                    //EnterUser(user);
                    System.out.println("Found user account");
                    break; 
                }
            }
        }
        
        if(loggedInUser != null){
            System.out.println("User Found: " + loggedInUser.getUserID());
        } 
        else{
            System.out.println("Invalid username or password");
              JOptionPane.showMessageDialog(null, "Invalid Login Details", 
                "Login Error", JOptionPane.ERROR_MESSAGE);
        ClearText();
        }
    }
    
    /*
    private void EnterUser(User user){
        
        switch (user.getUserID()) {
            case "a":
                User_Administrator Admin = new User_Administrator(user.getUserID(), user.getUserName());
                Admin.setVisible(true);
                CloseLogin();
                break;
            case "s":
                User_Secretary Secretary = new User_Secretary(user.getUserID(), user.getUserName());
                Secretary.setVisible(true);
                CloseLogin();
                break;
            case "d1":
                User_Doctor Doctor1 = new User_Doctor(user.getUserID(), user.getUserName());
                Doctor1.setVisible(true);
                CloseLogin();
                break;  
            case "d2":
                User_Doctor Doctor2 = new User_Doctor(user.getUserID(), user.getUserName());
                Doctor2.setVisible(true);
                CloseLogin();
                break;
            case "d3":
                User_Doctor Doctor3 = new User_Doctor(user.getUserID(), user.getUserName());
                Doctor3.setVisible(true);
                CloseLogin();
                break;
            case "p1":
                User_Patient Patient1 = new User_Patient(user.getUserID(), user.getUserName());
                Patient1.setVisible(true);
                CloseLogin();
                break;
            case "p2":
                User_Patient Patient2 = new User_Patient(user.getUserID(), user.getUserName());
                Patient2.setVisible(true);
                CloseLogin();
                break;
            case "p3":
                User_Patient Patient3 = new User_Patient(user.getUserID(), user.getUserName());
                Patient3.setVisible(true);
                CloseLogin();
                break;
            default:
                break;
        }
    }*/
    
    private void ClearText()
    {
        User_txt.setText(null);
        Password_pfield.setText(null);
    }
    
    /*
    private void CheckDetails()
    {
        String inputUsername = User_txt.getText().toLowerCase();
        System.out.println(inputUsername);
        
        String inputPassword = Password_pfield.getText();
        System.out.println(inputPassword);
               
        if(inputUsername.equals("a") && inputPassword.equals("1"))
        {
            System.out.println("This is the admin page");
                    
            User_Administrator Admin = new User_Administrator(inputUsername);
            Admin.setVisible(true);
            
            CloseLogin();
        }
        else if(inputUsername.startsWith("s") && inputPassword.startsWith("2"))
        {
            System.out.println("This is the secretary page");
            
            User_Secretary Secretary = new User_Secretary(inputUsername);
            Secretary.setVisible(true);
            
            CloseLogin();
        }
        else if(inputUsername.startsWith("d") && inputPassword.startsWith("3"))
        {
            System.out.println("This is the doctors page");
            
            User_Doctor Doctor = new User_Doctor(inputUsername);
            Doctor.setVisible(true);
            
            CloseLogin();
        }
        else if(inputUsername.startsWith("p") && inputPassword.startsWith("4"))
        {
            System.out.println("This is the patients page");
            
            User_Patient Patient = new User_Patient(inputUsername);
            Patient.setVisible(true);
            
            CloseLogin();
        }
        else 
        {
        JOptionPane.showMessageDialog(null, "Invalid Login Details", 
                "Login Error", JOptionPane.ERROR_MESSAGE);
        ClearText();
        }
    } */
    
    private void CloseLogin() {
        this.setVisible(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateAcc_btn;
    private javax.swing.JButton Exit_btn;
    private javax.swing.JButton Login_btn;
    private javax.swing.JLabel Logon_lbl;
    private javax.swing.JLabel Password_lbl;
    private javax.swing.JPasswordField Password_pfield;
    private javax.swing.JLabel User_lbl;
    private javax.swing.JTextField User_txt;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
